language: bash
dist: xenial
sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - python

env:
  - GRAILS_VERSION=4.0.1      BASE=adoptopenjdk
  - GRAILS_VERSION=4.0.1      BASE=adoptopenjdk-openj9
  - GRAILS_VERSION=4.0.1      BASE=adoptopenjdk-alpine
  - GRAILS_VERSION=3.3.11     BASE=adoptopenjdk
  - GRAILS_VERSION=3.3.11     BASE=adoptopenjdk-openj9
  - GRAILS_VERSION=3.3.11     BASE=adoptopenjdk-alpine
  - GRAILS_VERSION=2.5.6      BASE=adoptopenjdk

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

before_script:
  - docker --version
  - |
    export IMAGE_TAG=$GRAILS_VERSION-$BASE
    docker build -t grails:$GRAILS_VERSION-$BASE --build-arg GRAILS_VERSION=$GRAILS_VERSION ./$BASE

script:
  - docker run -it --rm --name grails-$IMAGE_TAG grails:$IMAGE_TAG grails --version | grep -q $GRAILS_VERSION

after_script:
  - docker images

after_success:
  - eval $(aws ecr get-login --no-include-email --region sa-east-1)
  - docker tag grails:$IMAGE_TAG $dockerId/grails:$IMAGE_TAG
  - docker push $dockerId/grails:$IMAGE_TAG
  - echo "$dockerHubPass" | docker login -u "$dockerHubId" --password-stdin
  - docker tag grails:$IMAGE_TAG $dockerHubId/grails:$IMAGE_TAG
  - docker push $dockerHubId/grails:$IMAGE_TAG
