sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - python

before_install:
  - pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - docker pull openjdk:8-jdk

script:
  - docker --version
  - docker build -t grails:3.3.8 .

after_success:
  - eval $(aws ecr get-login --no-include-email --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker tag grails:3.3.8 $dockerId/grails:3.3.8
  - docker push $dockerId/grails:3.3.8