sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - python

language: generic

env:
  matrix:
    - GRAILS_VERSION=3.3.8    OS=ubuntu
    - GRAILS_VERSION=3.3.8    OS=alpine
    - GRAILS_VERSION=2.5.5    OS=ubuntu
    - GRAILS_VERSION=2.5.5    OS=alpine

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - docker pull openjdk:8-jdk

script:
  - docker --version
  - docker build -t grails:$GRAILS_VERSION-$OS -f Dockerfile.$OS --build-arg GRAILS_VERSION=$GRAILS_VERSION .

after_success:
  - eval $(aws ecr get-login --no-include-email --region sa-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker tag grails:$GRAILS_VERSION-$OS $dockerId/grails:$GRAILS_VERSION-$OS
  - docker push $dockerId/grails:$GRAILS_VERSION-$OS