language: bash
dist: xenial
sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - python

env:
  - GRAILS_VERSION=4.0.0      OS=stretch
  - GRAILS_VERSION=3.3.10     OS=stretch
  - GRAILS_VERSION=3.3.9      OS=stretch
  - GRAILS_VERSION=3.3.8      OS=stretch
  - GRAILS_VERSION=2.5.6      OS=stretch

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker pull adoptopenjdk:8-jdk-hotspot

before_script:
  - docker --version
  - |
    if [ -z $ENV ]; then
      export IMAGE_TAG=$GRAILS_VERSION-$OS
      docker build -t grails:$GRAILS_VERSION-$OS --build-arg GRAILS_VERSION=$GRAILS_VERSION ./$OS
    else
    export IMAGE_TAG=$GRAILS_VERSION-$OS-$ENV
      docker build -f ./$OS/Dockerfile.dev -t grails:$GRAILS_VERSION-$OS-$ENV --build-arg GRAILS_VERSION=$GRAILS_VERSION ./$OS
    fi

script:
  - docker run -it --rm --name grails-$IMAGE_TAG grails:$IMAGE_TAG grails --version | grep -q $GRAILS_VERSION


after_script:
  - docker images

after_success:
  - eval $(aws ecr get-login --no-include-email --region sa-east-1)
  - docker tag grails:$IMAGE_TAG $dockerId/grails:$IMAGE_TAG
  - docker push $dockerId/grails:$IMAGE_TAG
  - echo "$dockerHubPass" | docker login -u "$dockerHubId" --password-stdin
  - docker tag grails:$IMAGE_TAG $dockerHubId/grails:$IMAGE_TAG
  - docker push $dockerHubId/grails:$IMAGE_TAG
