defaults: &defaults
  docker:
    - image: docker:18.06.1-ce
      environment:
        GRAILS_VERSION: 3.3.8

version: 2
jobs:
  grails3:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t grails:3.3.8 --build-arg GRAILS_VERSION=3.3.8 .

  grails2:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t grails:2.5.5 --build-arg GRAILS_VERSION=2.5.5 .

workflows:
  version: 2

  build:
    jobs:
      - grails3
      - grails2