executors:
  docker-run-executor:
    docker:
      - image: docker:18.06.1-ce

version: 2.1
jobs:
  grails-3.3.8:
    executor: docker-run-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t grails:3.3.8 --build-arg GRAILS_VERSION=3.3.8 .

  grails-2.5.5:
    executor: docker-run-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t grails:2.5.5 --build-arg GRAILS_VERSION=2.5.5 .

workflows:
  version: 2

  build:
    jobs:
      - grails-3.3.8
      - grails-2.5.5