name: Docker Image CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        grails_version: [4.0.1, 3.3.11, 2.5.6]
        base: [adoptopenjdk, adoptopenjdk-alpine, corretto]
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t grails:${{ matrix.grails_version }}-${{ matrix.base }} --build-arg GRAILS_VERSION=${{ matrix.grails_version }} ./${{ matrix.base }}
