name: Docker Hub CI

on:
  push:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        grails_version: [4.0.5, 3.3.12, 2.5.6]
        jdk: [8]
        base: [adoptopenjdk, corretto]
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./jdk8/${{ matrix.base }}
          file: ./jdk8/${{ matrix.base }}/Dockerfile
          push: true
          tags: grails:${{ matrix.grails_version }}-${{ matrix.base }}
          build-args: |
            GRAILS_VERSION=${{ matrix.grails_version }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
