name: Docker Image CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11]
        base: [adoptopenjdk, adoptopenjdk-alpine, corretto]
        grails_version: [4.0.1, 3.3.11, 2.5.6]
        exclude:
          - jdk: 11
            grails_version: 3.3.11
          - jdk: 11
            grails_version: 2.5.6

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build -t grails:${{ matrix.grails_version }}-jdk${{ matrix.jdk }}-${{ matrix.base }} --build-arg GRAILS_VERSION=${{ matrix.grails_version }} ./jdk${{ matrix.jdk }}/${{ matrix.base }}

    - name: Test the Docker image
      run: docker run --rm --name grails-${{ matrix.grails_version }}-jdk${{ matrix.jdk }}-${{ matrix.base }} grails:${{ matrix.grails_version }}-jdk${{ matrix.jdk }}-${{ matrix.base }} grails --version | grep -i ${{ matrix.grails_version }}
